apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: phantom-server-eureka
  namespace: develop

spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: phantom-server-eureka
    spec:
      containers:
      - name: phantom-server-eureka
        image: nginx:1.13
        ports:
        - containerPort: 7000
        resources:
          limits:
            memory: 1000Mi